services:
  - type: web
    name: baseball-stats-ocr
    env: docker
    region: oregon
    plan: free
    branch: master
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: INIT_SECRET
        generateValue: true
      - key: UPLOAD_DIR
        value: ./uploads
